<?php

namespace App\Filament\Resources\Masterbarangs\Pages;

use App\Filament\Resources\Masterbarangs\MasterbarangResource;
use Filament\Actions\DeleteAction;
use Filament\Resources\Pages\EditRecord;

class EditMasterbarang extends EditRecord
{
    protected static string $resource = MasterbarangResource::class;

    protected function getHeaderActions(): array
    {
        return [
            DeleteAction::make(),
        ];
    }

    protected function mutateFormDataBeforeSave(array $data): array
    {
        $data['nama_barang'] = strtoupper($data['nama_barang']);
        return $data; // TODO: Change the autogenerated stub
    }

    protected function getRedirectUrl(): string
    {
        return $this->previousUrl ?? $this->getResource()::getUrl('index');
    }
}
